/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 computer3D.gltf 
Author: Tuuttipingu (https://sketchfab.com/Tuuttipingu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-computer-71daf747a9b54b9299cc495533141eb5
Title: Sci-fi Computer
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Computer3D(props) {
  const { nodes, materials } = useGLTF("/computer3D.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.scifi_computer_screen_0.geometry}
          material={materials.screen}
        />
        <mesh
          geometry={nodes.scifi_computer_computer_0.geometry}
          material={materials.computer}
        />
        <mesh
          geometry={nodes.scifi_computer_keyboard_0.geometry}
          material={materials.keyboard}
        />
        <mesh
          geometry={nodes.scifi_computer_keys_0.geometry}
          material={materials.keys}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/computer3D.gltf");
